FROM qbituniverse/ai-r-core-api:4.3.0.XXX

LABEL version="4.3.0.XXX-tidyverse" \
	  description="Core Image for use with R Api plus Tidyverse" \
	  maintainer="marcin.narloch@qbituniverse.com"

RUN R -e "install.packages('tidyverse', lib = '/usr/local/lib/R/site-library')"