FROM rocker/r-ver:4.3.0

LABEL version="4.3.0" \
	  description="Core Image for use with R Api" \
	  maintainer="marcin.narloch@qbituniverse.com"

RUN apt-get update -qq
RUN apt-get install -y libz-dev libssl-dev libcurl4-gnutls-dev libsodium-dev
RUN apt-get clean

RUN R -e "update.packages(lib.loc = '/usr/local/lib/R/library', ask = FALSE)"
RUN R -e "update.packages(lib.loc = '/usr/local/lib/R/site-library', ask = FALSE)"
RUN R -e "install.packages('plumber', lib = '/usr/local/lib/R/site-library')"

RUN rm -rf /usr/lib/R/library && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

EXPOSE 8000