FROM rocker/rstudio:4.3

LABEL version="4.3" \
	  description="Core Image for use with R Studio" \
	  maintainer="marcin.narloch@qbituniverse.com"

ENV ROOT=TRUE

RUN apt-get update -qq && \
	apt-get install -y \
	libz-dev \
	libssl-dev \
	libcurl4-gnutls-dev \
	libsodium-dev && \
	apt-get clean

RUN	R -e "update.packages(lib.loc = '/usr/local/lib/R/library', ask = FALSE)" && \
	R -e "update.packages(lib.loc = '/usr/local/lib/R/site-library', ask = FALSE)" && \
	rm -rf /usr/lib/R/library && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /tmp/* && \
	chown -R rstudio /home

COPY config/rstudio/rstudio-prefs.json /home/rstudio/.config/rstudio/