FROM qbituniverse/ai-r-core-rstudio:4.3.0

LABEL version="4.3.0-tidyverse" \
	  description="Core Image for use with R Studio plus Tidyverse" \
	  maintainer="marcin.narloch@qbituniverse.com"

RUN R -e "install.packages('tidyverse', lib = '/usr/local/lib/R/site-library')"