FROM qbituniverse/ai-r-core-rstudio:4.3.0

LABEL version="4.3.0-java" \
	  description="Core Image for use with R Studio plus Java" \
	  maintainer="marcin.narloch@qbituniverse.com"

RUN apt-get install -y default-jre default-jdk r-cran-rjava
RUN apt-get clean

RUN R CMD javareconf