FROM rocker/rstudio:4.0.3

LABEL version="4.0" \
	  description="Core Image for use with R Studio" \
	  maintainer="marcin.narloch@qbituniverse.com"

ENV ROOT=TRUE

RUN	R -e "update.packages(lib.loc = '/usr/local/lib/R/library', ask = FALSE)" && \
	R -e "update.packages(lib.loc = '/usr/local/lib/R/site-library', ask = FALSE)" && \
	rm -rf /usr/lib/R/library && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /tmp/* && \
	chown -R rstudio /home

COPY config/rstudio/rstudio-prefs.json /home/rstudio/.config/rstudio/