FROM rocker/r-ver:3.5.0

LABEL version="3.5" \
 	  description="Base Image for use with R Api Deployment" \
	  maintainer="marcin.narloch@qbituniverse.com"

RUN rm -rf /usr/lib/R/library && \
	mkdir -p /projects && \
	mkdir -p /projects/repositories && \
	R -e "update.packages(repos = 'http://cran.rstudio.com', lib.loc = '/usr/local/lib/R/library', ask = FALSE)" && \
	R -e "update.packages(repos = 'http://cran.rstudio.com', lib.loc = '/usr/local/lib/R/site-library', ask = FALSE)" && \
	R -e "install.packages('plumber', repos = 'http://cran.rstudio.com', lib = '/usr/local/lib/R/site-library', dependencies = TRUE)" && \
	rm -rf /var/lib/apt/lists/ && \
    rm -rf /tmp/downloaded_packages/ /tmp/*.rds

EXPOSE 8000