FROM qbituniverse/ai-r-core-studio-base:4.0.248

LABEL version="4.0" \
 	  description="Base Image for use with R Studio Development plus Java" \
	  maintainer="marcin.narloch@qbituniverse.com"

RUN apt-get update && \
	apt-get install -y \
	default-jdk \
	r-cran-rjava && \
    apt-get clean && \
	R CMD javareconf
	
RUN	rm -rf /usr/lib/R/library && \
	R -e "update.packages(lib.loc = '/usr/local/lib/R/library', ask = FALSE)" && \
	R -e "update.packages(lib.loc = '/usr/local/lib/R/site-library', ask = FALSE)" && \
	rm -rf /var/lib/apt/lists/ && \
    rm -rf /tmp/downloaded_packages/ /tmp/*.rds