pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .cicd/docker/rstudio
    - .cicd/ado/build-ai-r-core-rstudio.yaml
    - config/rstudio

pr: none

resources:
  repositories:
  - repository: platformops.dev
    type: github
    name: qbituniverse/platformops.dev
    endpoint: qbituniverse

stages:
- stage: DockerBuildRStudio
  displayName: 'Build Docker Images for RStudio'
  variables:
    imageRepository: qbituniverse/ai-r-core-rstudio
    imageTag: $(imageVersion).$(Build.BuildId)
    imageVersion: 'N/A'
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Images for RStudio'
    steps:
    - template: content/azure-devops/builds/assign-build-number.yaml@platformops.dev
      parameters:
        imageDockerfile: .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio
        imageTag: $(imageTag)

    - template: content/azure-devops/builds/build-push-docker-image-single-arch.yaml@platformops.dev
      parameters:
        imageDockerfile: .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)
        addLatestTag: true

    - template: content/azure-devops/builds/build-push-docker-image-single-arch.yaml@platformops.dev
      parameters:
        imageDockerfile: .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio-java
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)-java
        addLatestTag: false

    - template: content/azure-devops/builds/build-push-docker-image-single-arch.yaml@platformops.dev
      parameters:
        imageDockerfile: .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio-tidyverse
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)-tidyverse
        addLatestTag: false