pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .cicd/docker/rstudio
    - .cicd/ado/build-ai-r-core-rstudio.yaml
    - config/rstudio

pr: none

resources:
  repositories:
  - repository: azure-devops-extensions
    type: github
    name: qbituniverse/azure-devops-extensions
    endpoint: qbituniverse

stages:
- stage: DockerBuildRStudio
  displayName: 'Build Docker Images for RStudio'
  variables:
    imageRepository: qbituniverse/ai-r-core-rstudio
    imageTag: $(imageVersion).$(Build.BuildId)
    imageVersion: 'N/A'
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Images for RStudio'
    steps:
    - template: builds/build-assign-number.yaml@azure-devops-extensions
      parameters:
        imageDockerfile: .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio
        imageTag: $(imageTag)

    - template: builds/build-docker.yaml@azure-devops-extensions
      parameters:
        imageDockerfile: .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)
        addLatestTag: true

    - template: builds/build-docker.yaml@azure-devops-extensions
      parameters:
        imageDockerfile: .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio-java
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)-java
        addLatestTag: false

    - template: builds/build-docker.yaml@azure-devops-extensions
      parameters:
        imageDockerfile: .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio-tidyverse
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)-tidyverse
        addLatestTag: false
