pool:
  name: 'self-hosted-ado-agents'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .cicd/docker/rstudio
    - .cicd/ado/build-ai-r-core-rstudio-single-arch.yaml
    - config/rstudio

pr: none

resources:
  repositories:
  - repository: platformops.dev
    type: github
    name: qbituniverse/platformops.dev
    endpoint: qbituniverse

stages:
- stage: DockerBuild
  displayName: 'Build Single-Arch Docker Images for RStudio'
  variables:
    imageDockerfile: .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio
    imageRepository: qbituniverse/ai-r-core-rstudio
    imageTag: $(imageVersion).$(Build.BuildId)
    imageVersion: 'N/A'
  jobs:
  - job: DockerBuild
    displayName: 'Build Single-Arch Docker Images for RStudio'
    timeoutInMinutes: 0
    steps:
    - template: content/azure-devops/builds/assign-build-number.yaml@platformops.dev
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)

    - template: content/azure-devops/builds/build-push-docker-image-single-arch.yaml@platformops.dev
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)
        addLatestTag: true

    - template: content/azure-devops/builds/build-push-docker-image-single-arch.yaml@platformops.dev
      parameters:
        imageDockerfile: $(imageDockerfile)-java
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)-java
        addLatestTag: false

    - template: content/azure-devops/builds/build-push-docker-image-single-arch.yaml@platformops.dev
      parameters:
        imageDockerfile: $(imageDockerfile)-tidyverse
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)-tidyverse
        addLatestTag: false
