trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio-tidyverse
    - .cicd/ado/build-ai-r-core-rstudio-tidyverse.yaml

pr: none

resources:
  repositories:
  - repository: platformops.dev
    type: github
    name: qbituniverse/platformops.dev
    endpoint: qbituniverse

stages:
- stage: DockerBuild
  displayName: 'Build Multi-Arch Docker Images for RStudio'
  pool:
    name: self-hosted-ado-agents
    demands:
    - agent.name -equals ado-agent-amd64
  variables:
    imageDockerfile: .cicd/docker/rstudio/Dockerfile-ai-r-core-rstudio-tidyverse
    imageRepository: qbituniverse/ai-r-core-rstudio
    imageTag: $(imageVersion)
    imageVersion: 'N/A'
    imageArchitecture: linux/amd64,linux/arm64
  jobs:
  - job: DockerBuild
    displayName: 'Build Multi-Arch Docker Images for RStudio'
    timeoutInMinutes: 0
    steps:
    - template: content/azure-devops/builds/assign-build-number.yaml@platformops.dev
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)

    - template: content/azure-devops/builds/dockerhub-login.yaml@platformops.dev

    - template: content/azure-devops/builds/create-buildx.yaml@platformops.dev
      parameters:
        buildNumber: $(Build.BuildId)

    - template: content/azure-devops/builds/build-push-docker-image-multi-arch.yaml@platformops.dev
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)
        imageArchitecture: $(imageArchitecture)

    - template: content/azure-devops/builds/delete-buildx.yaml@platformops.dev
      parameters:
        buildNumber: $(Build.BuildId)